export type QuestionType = 'likert5' | 'likert4' | 'frequency' | 'yes_no'

export interface Question {
  id: string
  section: string
  sectionIndex: number
  text: string
  type: QuestionType
  reverseScored: boolean
  weight: number
  domain: string
  consistencyPairId?: string
}

export const SECTIONS = [
  'Attention Control',
  'Executive Function',
  'Working Memory',
  'Time Blindness',
  'Hyperfocus',
  'Impulsivity',
  'Emotional Regulation',
  'Functional Impairment',
  'Childhood Indicators',
  'Sleep & Recovery',
  'Burnout',
  'Digital Environment',
  'Consistency Checks',
]

export const LIKERT5_LABELS = [
  'Never',
  'Rarely',
  'Sometimes',
  'Often',
  'Always',
]

export const FREQUENCY_LABELS = [
  'Not at all',
  'A few days',
  'More than half the days',
  'Nearly every day',
  'Every day',
]

export const QUESTIONS: Question[] = [
  // ─── SECTION 1: ATTENTION CONTROL (8 questions) ───────────────────────────
  {
    id: 'ac_01',
    section: 'Attention Control',
    sectionIndex: 0,
    text: 'I find it difficult to sustain attention on tasks that are not interesting to me.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'attentionControl',
  },
  {
    id: 'ac_02',
    section: 'Attention Control',
    sectionIndex: 0,
    text: 'I can stay focused on a demanding task for more than 30 minutes without losing concentration.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.3,
    domain: 'attentionControl',
  },
  {
    id: 'ac_03',
    section: 'Attention Control',
    sectionIndex: 0,
    text: 'External noise or movement in my environment easily breaks my focus.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.1,
    domain: 'attentionControl',
  },
  {
    id: 'ac_04',
    section: 'Attention Control',
    sectionIndex: 0,
    text: 'I notice that my mind wanders frequently even during important conversations or meetings.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'attentionControl',
  },
  {
    id: 'ac_05',
    section: 'Attention Control',
    sectionIndex: 0,
    text: 'I can deliberately redirect my attention back to a task after being interrupted.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.0,
    domain: 'attentionControl',
  },
  {
    id: 'ac_06',
    section: 'Attention Control',
    sectionIndex: 0,
    text: 'I struggle to pay attention to details and often make careless errors at work.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.1,
    domain: 'attentionControl',
  },
  {
    id: 'ac_07',
    section: 'Attention Control',
    sectionIndex: 0,
    text: 'I find it hard to follow through on instructions that require sustained mental effort.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'attentionControl',
  },
  {
    id: 'ac_08',
    section: 'Attention Control',
    sectionIndex: 0,
    text: 'I can maintain focus in open-plan or busy work environments.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.0,
    domain: 'attentionControl',
  },

  // ─── SECTION 2: EXECUTIVE FUNCTION (10 questions) ─────────────────────────
  {
    id: 'ef_01',
    section: 'Executive Function',
    sectionIndex: 1,
    text: 'I often start tasks with good intentions but struggle to follow through to completion.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.3,
    domain: 'executiveFunction',
  },
  {
    id: 'ef_02',
    section: 'Executive Function',
    sectionIndex: 1,
    text: 'I can break large projects down into manageable steps and execute them in sequence.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.2,
    domain: 'executiveFunction',
  },
  {
    id: 'ef_03',
    section: 'Executive Function',
    sectionIndex: 1,
    text: 'I have difficulty prioritizing tasks when everything feels equally urgent.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'executiveFunction',
  },
  {
    id: 'ef_04',
    section: 'Executive Function',
    sectionIndex: 1,
    text: 'I find it easy to switch between different tasks or projects without losing track.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.1,
    domain: 'executiveFunction',
  },
  {
    id: 'ef_05',
    section: 'Executive Function',
    sectionIndex: 1,
    text: 'I struggle to organize my work environment, files, or materials in a systematic way.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.0,
    domain: 'executiveFunction',
  },
  {
    id: 'ef_06',
    section: 'Executive Function',
    sectionIndex: 1,
    text: 'I can plan ahead and anticipate the steps needed to complete future obligations.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.2,
    domain: 'executiveFunction',
  },
  {
    id: 'ef_07',
    section: 'Executive Function',
    sectionIndex: 1,
    text: 'I avoid starting tasks that require a lot of mental effort or sustained thinking.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.3,
    domain: 'executiveFunction',
  },
  {
    id: 'ef_08',
    section: 'Executive Function',
    sectionIndex: 1,
    text: 'My desk, inbox, or digital workspace tends to become cluttered and unmanageable.',
    type: 'likert5',
    reverseScored: true,
    weight: 0.9,
    domain: 'executiveFunction',
  },
  {
    id: 'ef_09',
    section: 'Executive Function',
    sectionIndex: 1,
    text: 'I use systems (e.g., calendars, to-do lists, reminders) effectively to manage my work.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.1,
    domain: 'executiveFunction',
  },
  {
    id: 'ef_10',
    section: 'Executive Function',
    sectionIndex: 1,
    text: 'I find it difficult to maintain routines or habits even when I know they are beneficial.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'executiveFunction',
  },

  // ─── SECTION 3: WORKING MEMORY (7 questions) ──────────────────────────────
  {
    id: 'wm_01',
    section: 'Working Memory',
    sectionIndex: 2,
    text: 'I frequently misplace important items like keys, phone, wallet, or documents.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.1,
    domain: 'workingMemory',
  },
  {
    id: 'wm_02',
    section: 'Working Memory',
    sectionIndex: 2,
    text: 'I forget what I was about to do when I walk into a room or switch contexts.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'workingMemory',
  },
  {
    id: 'wm_03',
    section: 'Working Memory',
    sectionIndex: 2,
    text: 'I can hold multiple pieces of information in mind while working on a complex problem.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.3,
    domain: 'workingMemory',
  },
  {
    id: 'wm_04',
    section: 'Working Memory',
    sectionIndex: 2,
    text: 'I forget important instructions or commitments shortly after being told them.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'workingMemory',
  },
  {
    id: 'wm_05',
    section: 'Working Memory',
    sectionIndex: 2,
    text: 'I frequently lose the thread of a conversation or what point I was trying to make.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.1,
    domain: 'workingMemory',
  },
  {
    id: 'wm_06',
    section: 'Working Memory',
    sectionIndex: 2,
    text: 'I need to write things down immediately or I will forget them.',
    type: 'likert5',
    reverseScored: true,
    weight: 0.9,
    domain: 'workingMemory',
  },
  {
    id: 'wm_07',
    section: 'Working Memory',
    sectionIndex: 2,
    text: 'I can accurately recall details from meetings or conversations without needing notes.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.1,
    domain: 'workingMemory',
  },

  // ─── SECTION 4: TIME BLINDNESS (7 questions) ──────────────────────────────
  {
    id: 'tb_01',
    section: 'Time Blindness',
    sectionIndex: 3,
    text: 'I often underestimate how long tasks will take me to complete.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'timeBlindness',
  },
  {
    id: 'tb_02',
    section: 'Time Blindness',
    sectionIndex: 3,
    text: 'I am frequently late for meetings, appointments, or deadlines.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.3,
    domain: 'timeBlindness',
  },
  {
    id: 'tb_03',
    section: 'Time Blindness',
    sectionIndex: 3,
    text: 'I lose track of time while working and am often surprised when hours have passed.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.1,
    domain: 'timeBlindness',
  },
  {
    id: 'tb_04',
    section: 'Time Blindness',
    sectionIndex: 3,
    text: 'I can accurately estimate how long a task will take before starting it.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.2,
    domain: 'timeBlindness',
  },
  {
    id: 'tb_05',
    section: 'Time Blindness',
    sectionIndex: 3,
    text: 'I procrastinate until the last moment and then rush to complete work.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'timeBlindness',
  },
  {
    id: 'tb_06',
    section: 'Time Blindness',
    sectionIndex: 3,
    text: 'I struggle to start tasks at the right time even when I have planned to do them.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.1,
    domain: 'timeBlindness',
  },
  {
    id: 'tb_07',
    section: 'Time Blindness',
    sectionIndex: 3,
    text: 'I have a clear sense of how much time I have available and I use it effectively.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.0,
    domain: 'timeBlindness',
  },

  // ─── SECTION 5: HYPERFOCUS (6 questions) ──────────────────────────────────
  {
    id: 'hf_01',
    section: 'Hyperfocus',
    sectionIndex: 4,
    text: 'When I am working on something engaging, I lose track of time completely.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.2,
    domain: 'hyperfocus',
  },
  {
    id: 'hf_02',
    section: 'Hyperfocus',
    sectionIndex: 4,
    text: 'I can enter a state of deep, uninterrupted focus when I am passionate about a task.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.3,
    domain: 'hyperfocus',
  },
  {
    id: 'hf_03',
    section: 'Hyperfocus',
    sectionIndex: 4,
    text: 'I become so absorbed in interesting work that I forget to eat, sleep, or take breaks.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.1,
    domain: 'hyperfocus',
  },
  {
    id: 'hf_04',
    section: 'Hyperfocus',
    sectionIndex: 4,
    text: 'My best work happens in intense bursts of focus rather than steady, consistent effort.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.2,
    domain: 'hyperfocus',
  },
  {
    id: 'hf_05',
    section: 'Hyperfocus',
    sectionIndex: 4,
    text: 'I find it very hard to disengage from an activity I am deeply interested in.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.0,
    domain: 'hyperfocus',
  },
  {
    id: 'hf_06',
    section: 'Hyperfocus',
    sectionIndex: 4,
    text: 'There is a dramatic difference in my productivity between tasks I love and tasks I find boring.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.1,
    domain: 'hyperfocus',
  },

  // ─── SECTION 6: IMPULSIVITY (7 questions) ─────────────────────────────────
  {
    id: 'im_01',
    section: 'Impulsivity',
    sectionIndex: 5,
    text: 'I blurt out answers or comments before others have finished speaking.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.1,
    domain: 'impulsivity',
  },
  {
    id: 'im_02',
    section: 'Impulsivity',
    sectionIndex: 5,
    text: 'I make decisions impulsively and later regret not thinking them through.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.3,
    domain: 'impulsivity',
  },
  {
    id: 'im_03',
    section: 'Impulsivity',
    sectionIndex: 5,
    text: 'I can wait patiently in lines, meetings, or conversations without becoming restless.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.0,
    domain: 'impulsivity',
  },
  {
    id: 'im_04',
    section: 'Impulsivity',
    sectionIndex: 5,
    text: 'I interrupt others during conversations without realizing it.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.1,
    domain: 'impulsivity',
  },
  {
    id: 'im_05',
    section: 'Impulsivity',
    sectionIndex: 5,
    text: 'I frequently change plans, directions, or commitments on a whim.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'impulsivity',
  },
  {
    id: 'im_06',
    section: 'Impulsivity',
    sectionIndex: 5,
    text: 'I find it hard to resist distractions or temptations even when I am trying to focus.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'impulsivity',
  },
  {
    id: 'im_07',
    section: 'Impulsivity',
    sectionIndex: 5,
    text: 'I can pause and think before reacting in frustrating or high-pressure situations.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.1,
    domain: 'impulsivity',
  },

  // ─── SECTION 7: EMOTIONAL REGULATION (8 questions) ────────────────────────
  {
    id: 'er_01',
    section: 'Emotional Regulation',
    sectionIndex: 6,
    text: 'I experience intense emotional reactions to minor setbacks or frustrations.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'emotionalRegulation',
  },
  {
    id: 'er_02',
    section: 'Emotional Regulation',
    sectionIndex: 6,
    text: 'I can manage feelings of stress without it significantly impacting my work performance.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.2,
    domain: 'emotionalRegulation',
  },
  {
    id: 'er_03',
    section: 'Emotional Regulation',
    sectionIndex: 6,
    text: 'I become easily overwhelmed when facing multiple demands or unexpected changes.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.3,
    domain: 'emotionalRegulation',
  },
  {
    id: 'er_04',
    section: 'Emotional Regulation',
    sectionIndex: 6,
    text: 'Criticism or negative feedback affects my ability to continue working for hours or days.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.1,
    domain: 'emotionalRegulation',
  },
  {
    id: 'er_05',
    section: 'Emotional Regulation',
    sectionIndex: 6,
    text: 'I have effective strategies for calming myself down when I feel stressed or anxious.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.1,
    domain: 'emotionalRegulation',
  },
  {
    id: 'er_06',
    section: 'Emotional Regulation',
    sectionIndex: 6,
    text: 'I experience significant mood fluctuations that affect my productivity throughout the day.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'emotionalRegulation',
  },
  {
    id: 'er_07',
    section: 'Emotional Regulation',
    sectionIndex: 6,
    text: 'I am aware of my emotional state and can prevent it from derailing my focus.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.1,
    domain: 'emotionalRegulation',
  },
  {
    id: 'er_08',
    section: 'Emotional Regulation',
    sectionIndex: 6,
    text: 'Rejection or perceived failure triggers an intense emotional response in me.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.0,
    domain: 'emotionalRegulation',
  },

  // ─── SECTION 8: FUNCTIONAL IMPAIRMENT (6 questions) ──────────────────────
  {
    id: 'fi_01',
    section: 'Functional Impairment',
    sectionIndex: 7,
    text: 'My attention or focus issues have negatively impacted my career progress or work performance.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.4,
    domain: 'functionalImpairment',
  },
  {
    id: 'fi_02',
    section: 'Functional Impairment',
    sectionIndex: 7,
    text: 'My relationships (professional or personal) have suffered due to my attention difficulties.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.3,
    domain: 'functionalImpairment',
  },
  {
    id: 'fi_03',
    section: 'Functional Impairment',
    sectionIndex: 7,
    text: 'I have missed important deadlines, appointments, or commitments due to focus or memory issues.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.3,
    domain: 'functionalImpairment',
  },
  {
    id: 'fi_04',
    section: 'Functional Impairment',
    sectionIndex: 7,
    text: 'I feel my cognitive challenges are holding me back from reaching my full potential.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.4,
    domain: 'functionalImpairment',
  },
  {
    id: 'fi_05',
    section: 'Functional Impairment',
    sectionIndex: 7,
    text: 'I frequently underperform relative to my own abilities or what I know I am capable of.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.3,
    domain: 'functionalImpairment',
  },
  {
    id: 'fi_06',
    section: 'Functional Impairment',
    sectionIndex: 7,
    text: 'My attention challenges require significant compensatory effort (extra time, reminders, support).',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'functionalImpairment',
  },

  // ─── SECTION 9: CHILDHOOD INDICATORS (6 questions) ────────────────────────
  {
    id: 'ci_01',
    section: 'Childhood Indicators',
    sectionIndex: 8,
    text: 'As a child, I was frequently told I was not living up to my potential at school.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.1,
    domain: 'childhoodIndicators',
  },
  {
    id: 'ci_02',
    section: 'Childhood Indicators',
    sectionIndex: 8,
    text: 'I was considered hyperactive, restless, or disruptive as a child or teenager.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'childhoodIndicators',
  },
  {
    id: 'ci_03',
    section: 'Childhood Indicators',
    sectionIndex: 8,
    text: 'I struggled significantly with organization, completing homework, or following classroom instructions as a child.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'childhoodIndicators',
  },
  {
    id: 'ci_04',
    section: 'Childhood Indicators',
    sectionIndex: 8,
    text: 'Teachers or parents regularly commented that I had trouble paying attention or focusing.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.3,
    domain: 'childhoodIndicators',
  },
  {
    id: 'ci_05',
    section: 'Childhood Indicators',
    sectionIndex: 8,
    text: 'I excelled academically or professionally when the subject matched my interests but struggled with everything else.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.1,
    domain: 'childhoodIndicators',
  },
  {
    id: 'ci_06',
    section: 'Childhood Indicators',
    sectionIndex: 8,
    text: 'I was formally assessed or diagnosed with attention or learning difficulties at any point in my life.',
    type: 'yes_no',
    reverseScored: false,
    weight: 1.4,
    domain: 'childhoodIndicators',
  },

  // ─── SECTION 10: SLEEP & RECOVERY (7 questions) ───────────────────────────
  {
    id: 'sr_01',
    section: 'Sleep & Recovery',
    sectionIndex: 9,
    text: 'I feel mentally exhausted even after a full night of sleep.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.3,
    domain: 'sleepRecovery',
  },
  {
    id: 'sr_02',
    section: 'Sleep & Recovery',
    sectionIndex: 9,
    text: 'I consistently get 7–8 hours of quality sleep on most nights.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.2,
    domain: 'sleepRecovery',
  },
  {
    id: 'sr_03',
    section: 'Sleep & Recovery',
    sectionIndex: 9,
    text: 'My mind races with thoughts when I try to sleep, making it difficult to wind down.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'sleepRecovery',
  },
  {
    id: 'sr_04',
    section: 'Sleep & Recovery',
    sectionIndex: 9,
    text: 'I feel sharp, alert, and focused within the first hour of waking up.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.1,
    domain: 'sleepRecovery',
  },
  {
    id: 'sr_05',
    section: 'Sleep & Recovery',
    sectionIndex: 9,
    text: 'I take regular breaks during the workday to recover mental energy.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.0,
    domain: 'sleepRecovery',
  },
  {
    id: 'sr_06',
    section: 'Sleep & Recovery',
    sectionIndex: 9,
    text: 'I frequently feel like I am running on empty by mid-afternoon.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.1,
    domain: 'sleepRecovery',
  },
  {
    id: 'sr_07',
    section: 'Sleep & Recovery',
    sectionIndex: 9,
    text: 'Weekends or time off genuinely restore my cognitive energy and focus.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.0,
    domain: 'sleepRecovery',
  },

  // ─── SECTION 11: BURNOUT (6 questions) ────────────────────────────────────
  {
    id: 'bu_01',
    section: 'Burnout',
    sectionIndex: 10,
    text: 'I feel emotionally drained and depleted by my work on a regular basis.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.3,
    domain: 'burnoutLoad',
  },
  {
    id: 'bu_02',
    section: 'Burnout',
    sectionIndex: 10,
    text: 'I have lost enthusiasm for work that I once found meaningful or exciting.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.3,
    domain: 'burnoutLoad',
  },
  {
    id: 'bu_03',
    section: 'Burnout',
    sectionIndex: 10,
    text: 'I feel cynical or detached from the outcomes and goals of my work.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.2,
    domain: 'burnoutLoad',
  },
  {
    id: 'bu_04',
    section: 'Burnout',
    sectionIndex: 10,
    text: 'I feel a sense of dread on Sunday evenings thinking about the week ahead.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.1,
    domain: 'burnoutLoad',
  },
  {
    id: 'bu_05',
    section: 'Burnout',
    sectionIndex: 10,
    text: 'My productivity has noticeably declined even though I am putting in the same effort.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.2,
    domain: 'burnoutLoad',
  },
  {
    id: 'bu_06',
    section: 'Burnout',
    sectionIndex: 10,
    text: 'I feel like I am going through the motions at work rather than being genuinely engaged.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.2,
    domain: 'burnoutLoad',
  },

  // ─── SECTION 12: DIGITAL ENVIRONMENT (5 questions) ────────────────────────
  {
    id: 'de_01',
    section: 'Digital Environment',
    sectionIndex: 11,
    text: 'I check my phone, email, or social media more than 20 times per day.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.1,
    domain: 'digitalEnvironment',
  },
  {
    id: 'de_02',
    section: 'Digital Environment',
    sectionIndex: 11,
    text: 'Notifications from apps, messages, or emails regularly interrupt my deep work sessions.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'digitalEnvironment',
  },
  {
    id: 'de_03',
    section: 'Digital Environment',
    sectionIndex: 11,
    text: 'I have set up systems to protect my focus time (Do Not Disturb, app blockers, etc.).',
    type: 'likert5',
    reverseScored: false,
    weight: 1.1,
    domain: 'digitalEnvironment',
  },
  {
    id: 'de_04',
    section: 'Digital Environment',
    sectionIndex: 11,
    text: 'I find myself mindlessly scrolling social media or news even during work hours.',
    type: 'likert5',
    reverseScored: true,
    weight: 1.2,
    domain: 'digitalEnvironment',
  },
  {
    id: 'de_05',
    section: 'Digital Environment',
    sectionIndex: 11,
    text: 'I can go several hours without checking my phone when I need to focus.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.0,
    domain: 'digitalEnvironment',
  },

  // ─── SECTION 13: CONSISTENCY CHECKS (5 questions) ─────────────────────────
  {
    id: 'cc_01',
    section: 'Consistency Checks',
    sectionIndex: 12,
    text: 'Overall, I am able to focus on tasks for extended periods without getting distracted.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.0,
    domain: 'attentionControl',
    consistencyPairId: 'ac_01',
  },
  {
    id: 'cc_02',
    section: 'Consistency Checks',
    sectionIndex: 12,
    text: 'In general, I complete the tasks I set out to do each day.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.0,
    domain: 'executiveFunction',
    consistencyPairId: 'ef_01',
  },
  {
    id: 'cc_03',
    section: 'Consistency Checks',
    sectionIndex: 12,
    text: 'Overall, I rarely forget things that are important to me.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.0,
    domain: 'workingMemory',
    consistencyPairId: 'wm_01',
  },
  {
    id: 'cc_04',
    section: 'Consistency Checks',
    sectionIndex: 12,
    text: 'In general, I manage my time well and meet my commitments.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.0,
    domain: 'timeBlindness',
    consistencyPairId: 'tb_02',
  },
  {
    id: 'cc_05',
    section: 'Consistency Checks',
    sectionIndex: 12,
    text: 'Overall, I feel in control of my focus and attention most of the time.',
    type: 'likert5',
    reverseScored: false,
    weight: 1.0,
    domain: 'attentionControl',
    consistencyPairId: 'ac_04',
  },
]

export const QUESTION_COUNT = QUESTIONS.length

export const getSectionQuestions = (section: string) =>
  QUESTIONS.filter((q) => q.section === section)

export const getQuestionById = (id: string) =>
  QUESTIONS.find((q) => q.id === id)

export const getDomainQuestions = (domain: string) =>
  QUESTIONS.filter((q) => q.domain === domain && !q.consistencyPairId)
